// Created by Jacob Hodgkins
#include "semantic/SemanticCatalog.h"

namespace msrip::semantic {

const std::vector<SemanticSymbol>& SemanticCatalog::symbols(){
    static const std::vector<SemanticSymbol> s={
        {0x3435,true,"BeginFirstIntermission","routine","Patch redirect from $2108; reached first-act setup enters the shared Ms. Pac-Man animation engine."},
        {0x344F,true,"BeginSecondIntermission","routine","Patch redirect from $21A1 plus reached animation-engine control flow."},
        {0x3469,true,"BeginThirdIntermission","routine","Patch redirect from $229A plus reached animation-engine control flow."},
        {0x3483,true,"BeginAttractBlinkyAnimation","routine","RST $20 attract-state target immediately after the Blinky introduction; selects animation pointer-set offset $24 then tail-jumps to the shared intermission/attract animation updater."},
        {0x3488,true,"BeginAttractPinkyAnimation","routine","RST $20 attract-state target immediately after the Pinky introduction; selects animation pointer-set offset $30 then tail-jumps to the shared intermission/attract animation updater."},
        {0x348D,true,"BeginAttractInkyAnimation","routine","RST $20 attract-state target immediately after the Inky introduction; selects animation pointer-set offset $3C then tail-jumps to the shared intermission/attract animation updater."},
        {0x3492,true,"BeginAttractSueAnimation","routine","RST $20 attract-state target immediately after the Sue introduction; selects animation pointer-set offset $48 then tail-jumps to the shared intermission/attract animation updater."},
        {0x3497,true,"BeginAttractMsPacAnimation","routine","RST $20 attract-state target immediately after the Ms. Pac-Man starring state; selects animation pointer-set offset $54 then tail-jumps to the shared intermission/attract animation updater."},
        {0x349C,true,"UpdateIntermissionAndAttractAnimations","routine","Reached dispatcher consumes animation bytecode pointer set and command stream."},
        {0x3556,true,"NormalizeAnimationDeltaNibble","routine","Called by the animation motion engine; converts signed sprite-coordinate deltas into the packed nibble form consumed by the intermission updater."},
        {0x3611,true,"InitializeIntermissionAnimationState","routine","Called when the intermission/attract animation state is inactive; selects the six animation program pointers and initializes shared animation state."},
        {0x361F,true,"LoadAnimationProgramPointerSet","routine","Reached routine indexes $81F0 and copies six little-endian program pointers."},
        {0x3641,true,"SelectAnimationSpritePositionPointer","routine","Animation helper selects $4DC6 for slot six and $4CFE for the other sprite slots before position updates."},
        {0x364E,true,"SelectSongForCurrentLevel","routine","Patch redirect from $2D62; reached sound path selects the Ms. Pac-Man song index before returning to the wave processor."},
        {0x366F,true,"ApplyGhostTunnelSlowFlag","routine","Patch redirect from $2060; reached code tests maze color bit 6 and sets the ghost tunnel-slowdown flag."},
        {0x3678,true,"ClearFruitScoreSprite","routine","Patch redirect from timed task $100B; clears the fruit score sprite position and returns."},
        {0x367F,true,"UnusedMsPacSpriteFrameHelper","dead_routine","residual ownership closure byte-complete dead-code island; computes an Ms. Pac-Man sprite frame and returns."},
        {0x3E5C,true,"UpdateAttractModeController","routine","Patched attract-mode control path and RST $20 state dispatcher."},
        {0x3E8B,true,"AttractShowMsPacTitle","routine","RST $20 attract-state target; queues the Ms. Pac-Man title text, initializes the marquee counter, then advances the attract state."},
        {0x3E96,true,"AttractDrawMidwayLogo","routine","RST $20 attract-state target; calls the Ms. Pac-Man Midway logo/copyright renderer then advances the attract state."},
        {0x3E9C,true,"AttractShowBlinky","routine","RST $20 attract-state target; queues Blinky introduction text then advances the attract state."},
        {0x3EA2,true,"AttractShowPinky","routine","RST $20 attract-state target; queues the transition/Pinky introduction text sequence then advances the attract state."},
        {0x3EAB,true,"AttractShowInky","routine","RST $20 attract-state target; queues Inky introduction text then advances the attract state."},
        {0x3EB1,true,"AttractShowSue","routine","RST $20 attract-state target; queues Sue introduction text then advances the attract state."},
        {0x3EB7,true,"AttractShowMsPacStarring","routine","RST $20 attract-state target; queues Ms. Pac-Man introduction text then advances the attract state."},
        {0x3EBD,true,"AttractShowWith","routine","RST $20 attract-state target; queues the WITH text then advances the attract state."},
        {0x3EC3,true,"AttractShowStarring","routine","RST $20 attract-state target; queues STARRING text then advances the attract state."},
        {0x3EC9,true,"BeginAttractDemoMaze","routine","RST $20 attract-state target; clears lives and tail-jumps to the demo-maze state transition."},
        {0x3ED0,true,"UpdateMarqueeBulbs","routine","Reached marquee bulb animation consumer for $3F80 address table."},
        {0x39E0,true,"UnusedLegacyTableCopyHelper","dead_routine","residual ownership closure byte-complete dead helper indexing the adjacent $39F2 pair table."},
        {0x3A00,true,"UnusedSetLivesToOneHelper","dead_routine","residual ownership closure exact three-instruction helper: set lives to one and return."},
        {0x3FF8,false,"EnableDaughterboardDecoderAndReturn","routine","Decoder-enable trap root: opcode fetch at $3FF8 switches the daughterboard decoder on, exposes U7 byte $C9, and immediately returns."},
        {0x869C,true,"UpdateMsPacSpriteFacingEast","routine","Patched direction-specific Ms. Pac-Man sprite animation path."},
        {0x86B1,true,"UpdateMsPacSpriteFacingSouth","routine","Patched direction-specific Ms. Pac-Man sprite animation path."},
        {0x86C5,true,"UpdateMsPacSpriteFacingWest","routine","Patched direction-specific Ms. Pac-Man sprite animation path."},
        {0x86D9,true,"UpdateMsPacSpriteFacingNorth","routine","Patched direction-specific Ms. Pac-Man sprite animation path."},
        {0x86EE,true,"UpdateBouncingFruit","routine","Reached fruit position/path update code; patch redirect from $0EAD."},
        {0x8747,true,"CheckAndSpawnFruit","routine","Reached fruit-release checks at 64/176 dots and fruit initialization path."},
        {0x8793,true,"ClampFruitHistoryDisplayLevel","routine","Patch redirect from $2BF4; clamps displayed fruit level to the final normal fruit."},
        {0x8818,true,"CheckFruitCollisionAndScore","routine","Patch redirect from $19AD; reached code compares Pac-Man and bouncing-fruit coordinates and handles fruit consumption."},
        {0x87CD,true,"SelectRandomFruitPath","routine","Reached random selection of one of four route descriptors for current maze."},
        {0x87E4,true,"FinalizeFruitRouteSelection","routine","Shared fruit-route continuation reached both after random route selection and the fixed fallback path; stores the route timing/state byte and returns."},
        {0x946A,true,"SelectMazeAndPrepareRender","routine","Patch redirect from $241C; chooses current maze stream."},
        {0x947C,true,"PreparePelletMapForDrawing","routine","Patch redirect from $244B; selects current maze pellet map."},
        {0x9481,true,"PreparePelletMapForReadback","routine","Patch redirect from $248A; selects pellet map for eaten-dot state processing."},
        {0x9484,true,"PreparePelletMapCommon","routine","Shared continuation reached by both pellet-map drawing and readback entries; resolves the current maze pellet-map pointer and initializes the common destination/index registers."},
        {0x94A1,true,"CheckMazePelletCompletion","routine","Reached pellet-count comparison using per-maze count pointer table."},
        {0x94BD,true,"ResolvePerMazeTablePointer","routine","Reached helper maps level -> maze index -> little-endian per-maze table pointer."},
        {0x94EC,true,"DrawPowerPelletsForCurrentMaze","routine","Patch redirect from $2472; consumes per-maze power-pellet address table."},
        {0x9504,true,"RestorePowerPelletsForCurrentMaze","routine","Patch redirect from $24B4; restores current-maze energizer state after death."},
        {0x9524,true,"FlashPowerPelletsForCurrentMaze","routine","Patch redirect from $0C21; consumes per-maze energizer addresses."},
        {0x9559,true,"LoadInkyDirectionForRandomDestination","routine","Patch redirect from $27BB; loads Inky direction then joins the shared random ghost-destination selector."},
        {0x955E,true,"LoadClydeDirectionForRandomDestination","routine","Patch redirect from $2803; loads Clyde direction then joins the shared random ghost-destination selector."},
        {0x9561,true,"ChooseRandomGhostDestination","routine","Patch redirect from ghost corner logic; selects a random destination quadrant."},
        {0x9580,true,"ApplyMazeColorPatch","routine","Patch return path for per-level maze color selection."},
        {0x95C3,true,"ApplyEarlyMazeTunnelSlowZones","routine","Patch redirect from $24F9; applies maze-specific slow-tunnel color flags."},
        {0x95E3,true,"HandleMsPacPromptDrawing","routine","Patched prompt-dispatch target selected through the modified $23E0 RST $20 table; handles Ms.-specific prompt IDs before tail-jumping to DrawText."},
        {0x95F6,true,"PrepareStartScreenLogoAndBonusText","routine","Called by the Ms.-specific prompt handler; draws the Midway title mark and adjusts the extra-life prompt parameter from DIP-switch state."},
        {0x960B,true,"DrawBonusMsPacGraphic","routine","Reached table-driven renderer for the Ms. Pac-Man bonus-life graphic."},
        {0x9627,true,"RenderBonusMsPacGraphicElements","routine","Called by $960B; consumes four-byte color/graphic/screen records until $FF and writes both video and color RAM."},
        {0x963C,true,"ClearIntermissionIndicator","routine","Called by the Ms.-specific prompt path when READY is drawn; clears the intermission indicator at $4F00."},
        {0x9642,true,"DrawMidwayTitleLogoAndCopyright","routine","Called by attract/start-screen paths; queues Midway/copyright text and draws the title-screen mark directly into video/color RAM."},
        {0x9797,true,"PrepareIntermissionSpriteStateAndChannel1Song","routine","Patch redirect from $2CC1; reached code updates intermission sprite state and returns to the channel-1 song-table setup path."},

        {0x36A5,true,"TextRecordPointerTable","data","Reached DrawText indirect table; self-bounded by first record pointer $3713."},
        {0x3B08,true,"FruitHistorySpriteColorPairs","data","Reached fruit-history renderer consumes sprite/color pairs."},
        {0x3B30,true,"SoundEffectBankChannel1","data","Eight-byte sound-effect record format; two channel-1 records."},
        {0x3B40,true,"SoundEffectBankChannel2","data","Eight-byte sound-effect record format; eight channel-2 records."},
        {0x3B80,true,"SoundEffectBankChannel3","data","Eight-byte sound-effect record format; six records before timing table."},
        {0x3BB0,true,"SoundDurationTable","data","Reached sound engine masks duration index to 0..7."},
        {0x3BB8,true,"SoundFrequencyTable","data","Reached sound engine masks pitch index to 0..15."},
        {0x3F80,true,"MarqueeScreenAddressTable","data","Reached marquee routine proves exact accessed address-table union."},

        {0x81F0,true,"AnimationProgramPointerTable","data","Reached animation initializer copies six pointers per selected act/attract slot."},
        {0x8250,true,"AnimationProgramBytecodeBank","data","Independently parsed F0/F1/F2/F3/F5/F6/F7/F8/FF animation command grammar."},
        {0x8614,true,"AnimationSpriteSequenceBank","data","FF-terminated sprite-code sequences referenced by animation bytecode."},
        {0x879D,true,"FruitDescriptorTable","data","Reached fruit selection consumes seven three-byte shape/color/score descriptors."},
        {0x87F8,true,"FruitEntryPathPointerTable","data","Four per-maze fruit-entry route descriptor pointers."},
        {0x8800,true,"FruitExitPathPointerTable","data","Four per-maze fruit-exit route descriptor pointers."},
        {0x8808,true,"FruitFallbackRouteData","data","Fixed fallback fruit route consumed when current route completes."},
        {0x8841,true,"FruitSubpixelDeltaVectors","data","128-byte movement delta lookup reached from bouncing-fruit updater."},
        {0x88C1,true,"Maze1CommandStream","data","Zero-terminated maze drawing command stream selected by $9474 table."},
        {0x8A3B,true,"Maze1PelletMap","data","Exactly 30x8 pellet-offset bytes consumed by pellet renderer."},
        {0x8BAE,true,"Maze2CommandStream","data","Zero-terminated maze drawing command stream selected by $9474 table."},
        {0x8D27,true,"Maze2PelletMap","data","Exactly 30x8 pellet-offset bytes consumed by pellet renderer."},
        {0x8EA8,true,"Maze3CommandStream","data","Zero-terminated maze drawing command stream selected by $9474 table."},
        {0x9018,true,"Maze3PelletMap","data","Exactly 30x8 pellet-offset bytes consumed by pellet renderer."},
        {0x9179,true,"Maze4CommandStream","data","Zero-terminated maze drawing command stream selected by $9474 table."},
        {0x92EC,true,"Maze4PelletMap","data","Exactly 30x8 pellet-offset bytes consumed by pellet renderer."},
        {0x9474,true,"MazeStreamPointerTable","data","Four maze command-stream pointers."},
        {0x9499,true,"PelletMapPointerTable","data","Four maze pellet-map pointers."},
        {0x94B5,true,"PelletCountPointerTable","data","Four pointers to per-maze pellet-count bytes."},
        {0x94DF,true,"LevelToMazeIndexTable","data","Thirteen-byte level-to-maze schedule."},
        {0x951C,true,"PowerPelletPointerTable","data","Four per-maze energizer-address table pointers."},
        {0x9578,true,"GhostDestinationPointerTable","data","Four per-maze ghost destination tables."},
        {0x95AE,true,"MazeColorByLevelTable","data","Per-level maze palette codes used by color patch."},
        {0x95DF,true,"TunnelSlowPointerTable","data","Pointers to early-maze ghost slow-zone tile lists."},
        {0x9616,true,"BonusMsPacGraphicRecords","data","Four table-driven graphic/color/screen-position records plus terminator."},
        {0x967D,true,"SongTableChannel2","data","Four song pointers for channel 2."},
        {0x9685,true,"SongTableChannel1","data","Four song pointers for channel 1."},
        {0x968D,true,"SongTableChannel3","data","Channel-3 song table / empty-song pointer region."},
        {0x97D0,true,"GccDeveloperMessage","data","Physical U6 tail string: GENERAL COMPUTER CORPORATION / Hello, Nakamura!"}
    };
    return s;
}

const SemanticSymbol* SemanticCatalog::find(std::uint16_t address,bool decoderEnabled){
    for(const auto& s:symbols()) if(s.address==address && s.decoderEnabled==decoderEnabled) return &s;
    return nullptr;
}

} // namespace msrip::semantic
